#!/bin/bash
#SBATCH -J nf-ZL_PREDICT_RNA_STRUCTURE_EXTRACT_SHAPE_DATA_(test_shape.bed)
#SBATCH -o /project/mengjiechen/leizheng/pipeline/predict_rna_structure/test/work/fb/f4100fccfb7849556389490318e033/.command.log
#SBATCH --no-requeue
#SBATCH --signal B:USR2@30
#SBATCH -c 6
#SBATCH -t 08:00:00
#SBATCH --mem-per-cpu 9216M
#SBATCH 
#SBATCH --account=pi-chuanhe
#SBATCH --job-name=atac
#SBATCH --output=atac.out
#SBATCH --error=atac.err
#SBATCH --time=35:00:00
#SBATCH --partition=caslake
#SBATCH --nodes=1
#SBATCH --mail-type=ALL
#SBATCH --mail-user=leizheng@uchicago.edu
    
NXF_CHDIR=/project/mengjiechen/leizheng/pipeline/predict_rna_structure/test/work/fb/f4100fccfb7849556389490318e033
### ---
### name: 'ZL:PREDICT_RNA_STRUCTURE:EXTRACT_SHAPE_DATA (test_shape.bed)'
### container: 'null'
### outputs:
### - 'shape'
### ...
set -e
set -u
NXF_DEBUG=${NXF_DEBUG:=0}; [[ $NXF_DEBUG > 1 ]] && set -x
NXF_ENTRY=${1:-nxf_main}


nxf_sleep() {
  sleep $1 2>/dev/null || sleep 1;
}

nxf_date() {
    local ts=$(date +%s%3N);
    if [[ ${#ts} == 10 ]]; then echo ${ts}000
    elif [[ $ts == *%3N ]]; then echo ${ts/\%3N/000}
    elif [[ $ts == *3N ]]; then echo ${ts/3N/000}
    elif [[ ${#ts} == 13 ]]; then echo $ts
    else echo "Unexpected timestamp value: $ts"; exit 1
    fi
}

nxf_env() {
    echo '============= task environment ============='
    env | sort | sed "s/\(.*\)AWS\(.*\)=\(.\{6\}\).*/\1AWS\2=\3xxxxxxxxxxxxx/"
    echo '============= task output =================='
}

nxf_kill() {
    declare -a children
    while read P PP;do
        children[$PP]+=" $P"
    done < <(ps -e -o pid= -o ppid=)

    kill_all() {
        [[ $1 != $$ ]] && kill $1 2>/dev/null || true
        for i in ${children[$1]:=}; do kill_all $i; done
    }

    kill_all $1
}

nxf_mktemp() {
    local base=${1:-/tmp}
    mkdir -p "$base"
    if [[ $(uname) = Darwin ]]; then mktemp -d $base/nxf.XXXXXXXXXX
    else TMPDIR="$base" mktemp -d -t nxf.XXXXXXXXXX
    fi
}

nxf_fs_copy() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  cp -fRL $source $target/$basedir
}

nxf_fs_move() {
  local source=$1
  local target=$2
  local basedir=$(dirname $1)
  mkdir -p $target/$basedir
  mv -f $source $target/$basedir
}

nxf_fs_rsync() {
  rsync -rRl $1 $2
}

nxf_fs_rclone() {
  rclone copyto $1 $2/$1
}

nxf_fs_fcp() {
  fcp $1 $2/$1
}

on_exit() {
    exit_status=${nxf_main_ret:=$?}
    printf -- $exit_status > /project/mengjiechen/leizheng/pipeline/predict_rna_structure/test/work/fb/f4100fccfb7849556389490318e033/.exitcode
    set +u
    exit $exit_status
}

on_term() {
    set +e
    [[ "$pid" ]] && nxf_kill $pid
}

nxf_launch() {
    /bin/bash -ue /project/mengjiechen/leizheng/pipeline/predict_rna_structure/test/work/fb/f4100fccfb7849556389490318e033/.command.sh
}

nxf_stage() {
    true
    # stage input files
    rm -f test_exon.bed
    rm -f test_shape.bed
    ln -s /project/mengjiechen/leizheng/pipeline/predict_rna_structure/test/rawdata/test_exon.bed test_exon.bed
    ln -s /project/mengjiechen/leizheng/pipeline/predict_rna_structure/test/rawdata/test_shape.bed test_shape.bed
}

nxf_unstage() {
    true
    [[ ${nxf_main_ret:=0} != 0 ]] && return
}

nxf_main() {
    trap on_exit EXIT
    trap on_term TERM INT USR2
    trap '' USR1

    [[ "${NXF_CHDIR:-}" ]] && cd "$NXF_CHDIR"
    NXF_SCRATCH=''
    [[ $NXF_DEBUG > 0 ]] && nxf_env
    touch /project/mengjiechen/leizheng/pipeline/predict_rna_structure/test/work/fb/f4100fccfb7849556389490318e033/.command.begin
    set +u
    set -u
    export TMPDIR="/project/mengjiechen/leizheng/tmp"
    export PATH="$PATH:/project/mengjiechen/leizheng/pipeline/predict_rna_structure/bin"
    [[ $NXF_SCRATCH ]] && cd $NXF_SCRATCH
    export NXF_TASK_WORKDIR="$PWD"
    nxf_stage

    set +e
    (set -o pipefail; (nxf_launch | tee .command.out) 3>&1 1>&2 2>&3 | tee .command.err) &
    pid=$!
    wait $pid || nxf_main_ret=$?
    nxf_unstage
}

$NXF_ENTRY
